development:
  S3_BUCKET_NAME: "larkenfarms"
  AWS_ACCESS_KEY_ID: "AKIAIQ6D7DI64E63YICA"
  AWS_SECRET_ACCESS_KEY: "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"

production:
  S3_BUCKET_NAME: "larkenfarms"
  AWS_ACCESS_KEY_ID: "AKIAIQ6D7DI64E63YICA"
  AWS_SECRET_ACCESS_KEY: "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"